import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import { DiDjango, DiJsBadge, DiHtml5, DiMongodb, DiNodejs, DiReact, DiPostgresql, DiPython } from "react-icons/di";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`Val's Portfolio`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Hero />
      <div className='mt-5 mb-12'>
        <h1 className='flex justify-center text-4xl font-bolder text-sky-400 p-8' >
          Skills:
        </h1>
        
        
        <div className='flex justify-center'>
          <ul className='inline-flex justify-center'>
            <li className='text-8xl p-2'>
              <DiDjango />
            </li>
            <li className='text-8xl p-2'>
              <DiJsBadge />
              <p className='text-xl p-1 flex justify-center'>JavaScript</p>
            </li>
            <li className='text-8xl p-2'>
              <DiHtml5 />
              <p className='text-xl p-1 flex justify-center'>HTML 5</p>
            </li>
            <li className='text-8xl p-2'>
              <DiMongodb />
              <p className='text-xl p-1 flex justify-center'>Mongodb</p>
            </li>
          </ul>
        </div>
        <div className='flex justify-center'>
          <ul className='inline-flex justify-center'>
            <li className='text-9xl p-2'> 
              <DiNodejs />
            </li>
            <li className='text-9xl p-2'>
              <DiReact />
              <p className='text-xl p-1 flex justify-center'>React</p>
            </li>
            <li className='text-9xl p-2'>
              <DiPostgresql />
              <p className='text-xl p-1 flex justify-center'>Postgresql</p>
            </li>
            <li className='text-9xl p-2'>
              <DiPython />
              <p className='text-xl p-1 flex justify-center'>Python</p>
            </li>

          </ul>
        </div>
      </div>
    </div>
  )
}
